apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: react-frontend
        image: myacr.azurecr.io/react-frontend:latest # Image reference updated dynamically by pipeline
        ports:
        - containerPort: 3000
----

apiVersion: v1
kind: Service
metadata:
  name: frontend-service   # This is the DNS service name
  namespace: frontend-dev  # Specify the namespace where the frontend is deployed
spec:
  selector:
    app: frontend   # This label should match the label used in the frontend Deployment
  ports:
    - protocol: TCP
      port: 80            # Service port (frontend will be accessible on this port)
      targetPort: 3000     # Port where the frontend container listens
